#### Numpy Assignment

In [1]:
import numpy as np

##### Basic Array Creation and Manipulation

1. Create a 1D array:

        Create a 1D array of numbers from 0 to 9.

In [22]:
arr_1 = np.array(range(0,10))
arr_1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

2. Create a 2D array:

        Create a 2D array of shape (3, 3) with all elements as zeros.
        Create a 2D array of shape (3, 3) with all elements as ones.

In [23]:
arr_2 = np.zeros([3,3])
print(f"array of zeros: \n{arr_2}")
arr_3 = np.ones([3,3])
print(f"\narray of ones: \n{arr_3}")

array of zeros: 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

array of ones: 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


3. Array with a range of numbers:

        Create an array with numbers from 10 to 50, with a step of 5.

In [24]:
arr_4 = np.array(range(10, 51, 5))
arr_4

array([10, 15, 20, 25, 30, 35, 40, 45, 50])

4. Array with evenly spaced numbers:

        Create an array with 5 evenly spaced numbers between 0 and 1.

In [25]:
arr_5 = np.array(np.linspace(0,1,5))
arr_5

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

##### Array Operations

5. Element-wise operations:

        Create two arrays of shape (3, 3). Perform element-wise addition, subtraction, multiplication, and division on these arrays.

In [118]:
arr_6 = np.random.randint(1,100,(3,3))
print(arr_6)
arr_7 = np.random.randint(1,100, (3,3))
print("\n", arr_7)

[[76 27 84]
 [46 24 32]
 [51 38 69]]

 [[69 74 76]
 [75 37 67]
 [80 36 13]]


In [119]:
arr_6 + arr_7

array([[145, 101, 160],
       [121,  61,  99],
       [131,  74,  82]])

In [120]:
arr_6 - arr_7

array([[  7, -47,   8],
       [-29, -13, -35],
       [-29,   2,  56]])

In [121]:
arr_6 * arr_7

array([[5244, 1998, 6384],
       [3450,  888, 2144],
       [4080, 1368,  897]])

In [122]:
arr_6 / arr_7

array([[1.10144928, 0.36486486, 1.10526316],
       [0.61333333, 0.64864865, 0.47761194],
       [0.6375    , 1.05555556, 5.30769231]])

6. Matrix multiplication:

        Create two 2D arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [123]:
arr_8 = np.random.randint(1, 100, (2,3))
arr_9 = np.random.randint(1, 100, (3,2))

print(arr_8)
print("\n", arr_9)

[[90 96 93]
 [ 6 82 18]]

 [[37 24]
 [58 56]
 [22 48]]


In [ ]:
# Since the shape of the arrays are different, we can't do element wise multiplication. We can do dot product on both the axis as below.
np.dot(arr_8, arr_9)

array([[10944, 12000],
       [ 5374,  5600]])

In [126]:
np.dot(arr_9, arr_8)

array([[ 3474,  5520,  3873],
       [ 5556, 10160,  6402],
       [ 2268,  6048,  2910]])

7. Sum and product:

        Create a 1D array and find the sum and product of its elements.

In [128]:
arr_10 = np.random.randint(1, 100, (5))
arr_10

array([50, 71, 83, 72, 23])

In [137]:
print(f"Sum of the array elements: {sum(arr_10)}")
print(f"Product of the array elements: {arr_10.prod()}")

Sum of the array elements: 299
Product of the array elements: 487940400


##### Indexing and Slicing

8. Accessing elements:

        Create a 2D array and access the element at row 2, column 1.

In [143]:
arr_11 = np.array(np.random.randint(1,100,(5,4)))
print(f"Array created: \n{arr_11}")
print(f"Element sliced: {arr_11[1,0]}")

Array created: 
[[94  1 23  8]
 [68 35 48 18]
 [99 19 23 18]
 [34 17 46 67]
 [88 45  1 33]]
Element sliced: 68


9. Slicing rows and columns:

        Slice the first two rows and the last two columns of a 2D array.

In [151]:
arr_12 = np.array(np.random.randint(1, 100, (4,5)))
print(f"Array created: \n{arr_12}")
print(f"\nFirst 2 rows: \n{arr_12[:2,:]}")
print(f"\nLast 2 columns: \n{arr_12[:,-2:]}")

Array created: 
[[89 60 14 60 72]
 [79 82 55 27 60]
 [45 59 24  2 34]
 [42 72 41 96 45]]

First 2 rows: 
[[89 60 14 60 72]
 [79 82 55 27 60]]

Last 2 columns: 
[[60 72]
 [27 60]
 [ 2 34]
 [96 45]]


10. Boolean indexing:

        Create a 1D array of numbers from 1 to 10. Extract the elements that are greater than 5.

In [157]:
arr_13 = np.array(np.random.randint(1, 10, 10))
print(f"Array created: {arr_13}")
print(f"Elements greater than 5: {arr_13[arr_13>5]}")

Array created: [2 3 8 6 5 8 2 7 9 6]
Elements greater than 5: [8 6 8 7 9 6]


##### Reshaping and Resizing

11. Reshape an array:

        Create a 1D array of 12 elements and reshape it into a 2D array of shape (3, 4).

In [10]:
arr_14 = np.array(np.random.randint(1,100,12))
arr_14 = arr_14.reshape(3,4)
arr_14

array([[99, 26, 60, 25],
       [74,  6, 19, 51],
       [88, 59, 36, 67]])

12. Flatten an array:

        Create a 2D array and flatten it into a 1D array.

In [18]:
arr_15 = np.array(np.random.randint(0,100,(3,4)))
print(f"Original array: \n{arr_15}")
print(f"Array after reshaping: \n{arr_15.reshape(-1)}")

Original array: 
[[61 99 38 90]
 [68 60 52 39]
 [56 71 62 10]]
Array after reshaping: 
[61 99 38 90 68 60 52 39 56 71 62 10]


##### Statistical Operations

13. Mean, median:

        Create an array and find its mean, median,

In [8]:
arr_16 = np.array(np.random.randint(1,100,10))
print(f"Array: \n{arr_16}")
print(f"Mean of the array: \n{arr_16.mean()}")
print(f"Mode of the array: \n{np.median(arr_16)}")

Array: 
[62  2  6 12 51  5 41 36 59 15]
Mean of the array: 
28.9
Mode of the array: 
25.5


14. Sum:

        Create a 2D array and find the sum

In [12]:
arr_17 = np.array(np.random.randint(1,100,(3,4)))
print(f"Array: \n{arr_17}")
print(f"Sum of the array: \n{arr_17.sum()}")

Array: 
[[ 7 15 17 69]
 [15 25 47  9]
 [ 4 55 32 79]]
Sum of the array: 
374


##### Broadcasting

15. Broadcasting addition:

        Create a 2D array and a 1D array. Add the 1D array to each row of the 2D array using broadcasting.

In [21]:
arr_18 = np.array(np.random.randint(1,10,(3,4)))
arr_19 = np.array(np.random.randint(1,10,4))

print(f"2D Array: \n{arr_18}")
print(f"1D Array: \n{arr_19}")

print(f"Sum of arrays: \n{arr_18+arr_19}")

2D Array: 
[[3 2 2 6]
 [8 9 6 6]
 [6 4 4 2]]
1D Array: 
[1 3 6 3]
Sum of arrays: 
[[ 4  5  8  9]
 [ 9 12 12  9]
 [ 7  7 10  5]]


16. Broadcasting multiplication:

        Create a 2D array and multiply each element by a scalar using broadcasting.

In [22]:
arr_20 = np.array(np.random.randint(1,10,(3,4)))
print(f"2D array: \n{arr_20}")
print(f"Product of 2: \n{arr_20 * 2}")

2D array: 
[[4 3 6 5]
 [1 4 2 4]
 [5 7 6 8]]
Product of 2: 
[[ 8  6 12 10]
 [ 2  8  4  8]
 [10 14 12 16]]


##### Linear Algebra

17. Transpose of a matrix:

        Create a 2D array and find its transpose.

In [23]:
arr_21 = np.array(np.random.randint(1,20,(4,5)))
print(f"2D array: \n{arr_21}")
print(f"Transpose of the array: \n{arr_21.T}")

2D array: 
[[18  7 17  7  7]
 [ 7  6  3 19  8]
 [18  8 17  9 11]
 [11 19  5  4 12]]
Transpose of the array: 
[[18  7 18 11]
 [ 7  6  8 19]
 [17  3 17  5]
 [ 7 19  9  4]
 [ 7  8 11 12]]


18. Inverse of a matrix:

        Create a 2D array of shape (2, 2) and find its inverse.

In [153]:
arr_22 = np.array(np.random.randint(0,10,(2,2)))
print(f"Array: \n{arr_22}")
print(f"Inverse of the array: \n{1/arr_22}")

Array: 
[[8 3]
 [1 4]]
Inverse of the array: 
[[0.125      0.33333333]
 [1.         0.25      ]]


19. Determinant of a matrix:

        Create a 2D array of shape (3, 3) and find its determinant.

In [154]:
arr_23 = np.array(np.random.randint(1,10,(3,3)))
print(f"3*3 array: \n{arr_23}")
print(f"Determinant of the array: \n{np.linalg.det(arr_23)}")

3*3 array: 
[[9 9 5]
 [4 6 9]
 [6 8 7]]
Determinant of the array: 
-56.00000000000002


##### Random Number Generation

21. Random array:

        Create a 3x3 array with random values between 0 and 1.

In [159]:
arr_24 = np.array(np.linspace(0,1,9)).reshape(3,3)
print(arr_24)

[[0.    0.125 0.25 ]
 [0.375 0.5   0.625]
 [0.75  0.875 1.   ]]


22. Random integers:

        Create a 4x4 array with random integers between 1 and 10.

In [161]:
arr_25 = np.array(np.random.randint(1,10,(4,4)))
arr_25

array([[1, 7, 8, 8],
       [3, 4, 6, 3],
       [9, 6, 5, 1],
       [6, 6, 7, 3]])